title: Kappa
description: >-
  CTF Team from Saint Petersburg
baseurl: "/"
url: "https://kappactf.ru"
github_username:  kappactf
email: blog@kappactf.ru

kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighterr: rouge
    extensions: fenced_code_blocks

markdown: kramdown
permalink: /:year-:month-:day-:title/

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-avatar

paginate: 5
paginate_path: /page:num/

