title: Kappa
description: >-
  CTF Team from Saint Petersburg
baseurl: "/"
url: "https://kappactf.ru"
github_username:  kappactf
email: blog@kappactf.ru

kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighterr: rouge
    extensions: fenced_code_blocks

markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-avatar

paginate: 5
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
