title: Kappa
email: kappa@kappactf.ru
description: >-
  Official blog of Kappa CTF Team from Saint Petersburg. Maybe we'll
  publish awesome write-ups and inform about new items in our shop.
baseurl: "/"
url: "https://kappactf.ru"
#twitter_username: jekyllrb
github_username:  kappactf

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
